name: 💡 Feature Request
description: Suggest a new feature or enhancement for ADK agents
title: "[FEATURE] "
labels: ["enhancement", "needs-feedback"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Great! We love new ideas. Please provide details about the feature you'd like to see.

  - type: dropdown
    id: feature_category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Agent Intelligence (LLM improvements)
        - Workflow Orchestration
        - Tool Integration
        - Multi-Agent Communication
        - User Interface/Experience
        - Performance & Scaling
        - Security & Governance
        - Monitoring & Analytics
        - API/Integration
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature to your work?
      options:
        - Critical (Blocking current work)
        - High (Important for upcoming work)
        - Medium (Would be helpful)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current challenge or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: How would different users interact with this feature?
      placeholder: |
        As a [user type], I want [functionality] so that [benefit]
        
        Example:
        As a developer, I want agent templates so that I can quickly create new agents
      render: markdown

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
      render: markdown

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature might be?
      options:
        - Simple (Few hours to 1 day)
        - Medium (2-5 days)
        - Large (1-2 weeks)
        - Extra Large (2+ weeks)
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: governance_check
    attributes:
      label: Governance Considerations
      description: Please check any that apply to this feature
      options:
        - label: This feature may impact security or privacy
        - label: This feature may require compliance review
        - label: This feature may need ethics board approval
        - label: This feature impacts customer-facing functionality

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or related references
      placeholder: Links, screenshots, or other helpful context
